helmDefaults:
  args:
    - "--wait"
    - "--timeout=600"
    - "--force"
    - "--reset-values"

releases:

################################################################################
## Caliban #####################################################################
################################################################################

#
# References:
#   - [web address of Helm chart's YAML file]
#
- name: caliban
  namespace: deepcell
  labels:
    chart: caliban
    component: deepcell
    namespace: deepcell
    vendor: vanvalenlab
    default: true
  chart: '{{ env "CHARTS_PATH" | default "/conf/charts" }}/caliban'
  version: 0.1.0
  values:
    - replicas: 1

      image:
        repository: vanvalenlab/caliban
        tag: 0.1
        pullPolicy: Always

      resources:
        requests:
          cpu: 150m
          memory: 256Mi
        # limits:
        #   cpu: 100m
        #   memory: 512Mi

      service:
        type: "ClusterIP"

        httpIngressEnabled: true
        internalHttpPort: 5000
        httpTargetPort: 5000
        externalHttpPort: 5000

        httpsIngressEnabled: false
        internalHttpsPort: 8443
        httpsTargetPort: 8443
        externalHttpsPort: 8443

      ingress:
        enabled: true
        path: /caliban
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/rewrite-target: /
          nginx.ingress.kubernetes.io/ssl-redirect: "false"
          nginx.ingress.kubernetes.io/proxy-body-size: "1g"

      env:
        PORT: 5000

      secrets:
        AWS_ACCESS_KEY_ID: '{{ env "AWS_ACCESS_KEY_ID" | default "NA" }}'
        AWS_SECRET_ACCESS_KEY: '{{ env "AWS_SECRET_ACCESS_KEY" | default "NA" }}'
        AWS_S3_BUCKET: '{{ env "AWS_S3_BUCKET" | default "NA" }}'
        GCLOUD_STORAGE_BUCKET: '{{ env "GKE_BUCKET" | default "NA" }}'
        GCLOUD_PROJECT_ID: '{{ env "PROJECT" | default "NA" }}'
